server:
  port: 8080
spring:
  application:
    name: "spring-boot-3-demo"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
adapter:
  restconsumer:
    timeout: 5000
    url: "https://jsonplaceholder.typicode.com/users"
